# Generated by Django 2.1.5 on 2019-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email',
        ),
        migrations.AlterField(
            model_name='form',
            name='coursera_username',
            field=models.EmailField(max_length=50),
        ),
    ]
